### ISSUE TITLE
Invalid numeric argument Error building LsQuic in Windows/Visual Studio

### ISSUE THREAD

**Issue by Kait0** [litespeedtech/lsquic-client#10]
I am currently trying to compile the lsquic client on a windows 10 system using your guide: [guide](https://github.com/litespeedtech/lsquic-client/blob/master/BUILD-WINDOWS.md)  

All the steps until the compilation in windows studio 2015 did work.  
Once I tried compiling the client I got numerous errors. (who where all not solved by multiple building)  
First an error that says invalid numeric argument '\Wextra'  
[Wextra](https://i.imgur.com/ZQP5KjH.png)  
I could "fix" this one by commenting a line in the CMakeLists.txt file as it seems to be a flag that should only be set on linux systems from what I can tell.  
The next error(which appeared after compiling again) said  "invalid numeric argument '\Werror' "  
[Werror](https://i.imgur.com/ZxPebo3.png)  
Same fix as the previous error.  
[CMakeLists.txt](https://i.imgur.com/PoOSvhW.png)  
After that I got even more errors (I think most of them are the once mentioned in the guide)  
The outstanding error again said: "invalid numeric argument '\Wno-unused-value' "  
[Wno](https://i.imgur.com/gKjIXr8.png)  
Unfortunately I couldn't fix this one since it did not appear in the CmakeList.txt file.  

Now I don't know whether this is a problem on my end or with the client so if somebody understands these error codes it would be nice if you could help me out.  
The bug happended on both debug and release on a x64 machiene.

**Comment by dtikhonov** [comment]
From the screenshot you provided, it seems that the non-Windows portion of CMakeLists.txt is being used.  We detect Windows by the value of  `CMAKE_C_COMPILER` ([line 32](https://github.com/litespeedtech/lsquic-client/blob/e8bd737db4830fe07450280e028fe2e30c447560/CMakeLists.txt#L32)).

Could you tell what the value of `CMAKE_C_COMPILER` is on your system?  You could add the following line to your CMakeLists.txt:

```

**Comment by Kait0** [comment]
![unbenannt3](https://user-images.githubusercontent.com/4252687/38943148-f95135ae-4330-11e8-968e-cc283ba1a8fe.PNG)
It has the filenpath as compiler

**Comment by dtikhonov** [comment]
I see.  I tried to address this on branch [201804181205-detect-ms-compiler-better](https://github.com/litespeedtech/lsquic-client/tree/201804181205-detect-ms-compiler-better) (just pushed).  Could you please give it a shot?

**Comment by Kait0** [comment]
I tried it on your branch and the initial error doesn't occur anymore. There is another bug now the programm is trying to find lsquic.lib in an empty folder.
![capture](https://user-images.githubusercontent.com/4252687/38945939-36b72118-4338-11e8-8d6a-c2a0265c81c8.PNG)

windows search led me to the cmakelists.txt again where the file is mentioned in target_link_libraries.
![capture2](https://user-images.githubusercontent.com/4252687/38945944-3acee3b2-4338-11e8-9279-823b8dcaa589.PNG)

**Comment by rperper** [comment]
We'd kind of expect that.  If zlib or any of the other dependencies aren't found, it can't build lsquic.lib.  So make sure that all of your dependencies are in place.

**Comment by Kait0** [comment]
Installing the librarys again fixed the problem. Not sure why they weren't installed anymore just installed them yesterday. Maybe because I switched the git branch.

Have one last error  or rather warning where the compiler can't find certain functions.
![capture3](https://user-images.githubusercontent.com/4252687/38954435-ec700150-4351-11e8-918c-21f4cc65aac3.PNG)

the error above does go away when I build lsquic again only the marked 4 stay.
In which file should those be defined? From the name I expect them to be something projectintern and not releated to external dependencys.

**Comment by dtikhonov** [comment]
These functions have been obsoleted recently and we forgot to update the Windows version.  We'll take care of it.  Stay tuned.

**Comment by rperper** [comment]
Sorry, Dmitri is right, I gave you incorrect information.  We need to update the build.  Thanks for your help!  We'll get to you shortly.

**Comment by litespeedtech** [comment]
We believe the issues identified in this bug report have been addressed.  Please give it a shot using the master branch.

**Comment by Kait0** [comment]
I can confirm that the issue is fixed. Thank you for your quic responses.

**Comment by Kait0** [comment]
I can confirm that the issue is fixed. Thank you for your quic responses.
