### ISSUE TITLE
Assertion Failed Runtime Error when trying to run the standard example on Windows

### ISSUE THREAD

**Issue by Kait0** [litespeedtech/lsquic-client#13]
![unbenannt3](https://user-images.githubusercontent.com/4252687/39064315-6ab48536-44ce-11e8-9c49-cfe0ce03e5b9.PNG)
When trying to execute lsquic using the standard example in EXAMPLES.txt in Debug mode the program will crash with an Assertion Failed Error as shown in the picture above. I doesn't matter wether ipv4 or ipv6 is used.  The error happens in lsquic_engine.c
![unbenannt](https://user-images.githubusercontent.com/4252687/39064471-ea57c564-44ce-11e8-8f9d-0ebedbe52686.png)
![unbenannt2](https://user-images.githubusercontent.com/4252687/39064473-ee44ba10-44ce-11e8-9a4f-06fe7c005a3f.png)
These are the flags that are shown in the debugger.

When executed in release mode the programm will just go into an infinite loop.
Since it is about flags again it might have something to do with issue #10

**Comment by dtikhonov** [comment]
@Kait0, any chance you could attach a backtrace?

**Comment by Kait0** [comment]
![capture4](https://user-images.githubusercontent.com/4252687/39068382-6c50ae7a-44dc-11e8-9121-ce6e0fa1e6b4.PNG)
like this?

**Comment by dtikhonov** [comment]
Thank you!

I have to say, it looks normal.  Could you please run the program with `-L debug` and attach the log messages to the bug report?

**Comment by dtikhonov** [comment]
OK, I can reproduce it!  (Was testing wrong branch before!)

**Comment by litespeedtech** [comment]
Marking FIXED.

**Comment by Kait0** [comment]
Error is fixed for me too. Program now runs without crash. Is the example setup supposed to print anything on the console?

**Comment by Kait0** [comment]
![capture5](https://user-images.githubusercontent.com/4252687/39072069-99063c5c-44e9-11e8-97e5-5183751cd7c8.PNG)
is it possible that the google server just is not responding? program wait for a while and than terminates without printing anything when I run it

**Comment by dtikhonov** [comment]
Yes, it is possible.  You can turn on logging to see what's going on.  For example:

`-l event=debug,engine=debug`

or

`-L debug` (this turns on logging for all the modules).

**Comment by dtikhonov** [comment]
It is also possible that our IPv6 support is simply broken on Windows -- I don't think we've ever tested it, frankly.  I just tried using an IPv6 address on my Windows box and it does not work.

Sorry.  I guess, stick to IPv4 for now?  I'll open a bug for IPv6.

**Comment by Kait0** [comment]
same thing with ipv4 you can see it in the picture above. I tried both versions

**Comment by dtikhonov** [comment]
Oh, right.  Hmm.  Well, what do the log messages say?

**Comment by Kait0** [comment]
![grafik](https://user-images.githubusercontent.com/4252687/39072755-c70501cc-44eb-11e8-88f2-bb79132bc392.png)

**Comment by Kait0** [comment]
Full Log
![grafik](https://user-images.githubusercontent.com/4252687/39072899-4c68acb0-44ec-11e8-962d-901f67e8b118.png)
![grafik](https://user-images.githubusercontent.com/4252687/39072937-64c1a424-44ec-11e8-9427-e06a2ed83247.png)
than it goes on like that for a while and this is the end
![grafik](https://user-images.githubusercontent.com/4252687/39072995-8e8b8374-44ec-11e8-9f45-aed1f0414735.png)

**Comment by dtikhonov** [comment]
It looks like no packets get back to you.  Could it be your network?  Does Chrome use QUIC when you browse to www.google.com?

**Comment by Kait0** [comment]
![grafik](https://user-images.githubusercontent.com/4252687/39074011-19529aee-44f0-11e8-9c28-2f15f8cffd65.png)
wireshark reports a lot of quic packages being sent so I assume yes. I there a way to check in chrome itself?
By the way do you get a response when you run the example on the master branch?
