### ISSUE TITLE
Return response headers in pre-parsed form

### ISSUE THREAD

**Issue by Kait0** [litespeedtech/lsquic-client#21]
So from what it looks like the lsquic-client is using HTTP/1.1 right now (or at least the google server sends back an HTTP/1.1 answer)
![http1](https://user-images.githubusercontent.com/4252687/39367483-1ef5d190-4a37-11e8-8de2-c5a55b69efa2.png)

Now from what I know google quic is supposed to run underneath HTTP/2 shim
![quicstack](https://user-images.githubusercontent.com/4252687/39367590-81346f1a-4a37-11e8-9971-afabf01a7847.png)

Are there any plans to add HTTP/2 support to the client?

**Comment by dtikhonov** [comment]
This is an interface choice: the QUIC response is translated to HTTP/1.1.  Nevertheless, the library supports the full range of the HTTP/QUIC functionality, including push promises, and thus I do not agree with the title of this report.

It may be useful to return a response using an array of headers that do not have to be parsed again (which is the case with the current interface).  Perhaps we can add it to the wishlist?  (And pull requests are always welcome! 😄 )

**Comment by dtikhonov** [comment]
No, connection happens using QUIC -- there is no separate HTTP/2 layer.  That "shim" picture you posted is just a mental model.  HTTP/2 is pretty much HTTP/1.x in binary encoding with push promises.
