### ISSUE TITLE
Warning treated as error

### ISSUE THREAD

**Issue by Kait0** [litespeedtech/lsquic-client#24]
Since yesterday I can't build the windows version anymore (Linux still works)
I get an "Error	C2220	warning treated as error - no 'object' file generated	lshpack.c	line 5354"	error and the following warnings:
![capture](https://user-images.githubusercontent.com/4252687/39631877-c44e97d6-4fb3-11e8-8852-a3b8b0afe526.PNG)
Changing to the commit from 27/4/2018 fixes this problem so I believe this is a regression in the latest changes.

**Comment by dtikhonov** [comment]
Thank you for the report, we'll take care of it.

We don't do much Windows testing, as you can see 😄.  At some point we'll set up AppVeyor, so this sort of thing is caught early.

**Comment by litespeedtech** [comment]
This has been fixed in 075860c94bdbfa9ea4d928d1949d254dc7a3c47f -- closing.
