### ISSUE TITLE
Best multiple stream run practice(usage advice)

### ISSUE THREAD

**Issue by sergePSE** [litespeedtech/lsquic-client#38]
For my example of using lsquic library it's required to download sequentially pairs of web pair resources, but for the same hostname. So after downloading first 2 urls in parallel there is the next pair. Should I use the same created pair of "lsquic_stream"s? Or is it better after reading 0 bytes from http_client_on_read event, close used streams and create new ones for next pair of urls?

**Comment by dtikhonov** [comment]
A single stream corresponds to a single HTTP request/response exchange.  You cannot reuse a stream in the fashion you describe.  If the next pair of URLs is for the same host, create new streams; otherwise, you will need to create a new connection.

**Comment by sergePSE** [comment]
Thanks for answer. That is what I was looking for.
