### ISSUE TITLE
Multiple connections issue

### ISSUE THREAD

**Issue by sergePSE** [litespeedtech/lsquic-client#39]
I'm not sure, but there might be an issue, connected with maintaining multiple connections at the same time. I've tried to connect to the www.youtube.com(172.217.21.238) and www.google.com (216.58.213.228). But for the first one there is connection handshake established, for the second one not. In case of downloading a single www.google.com - connection is successful.
After creating an engine, all connections are created, then streams. After that lsquic_engine_process_conns is called. It seems like both connections send their hello packets on event packets_out, but response is processed only for the one. For the other one there is connection ID mismatch.
So finally there is a problem of storing 2 connections for the one engine at the same time.
https://github.com/sergePSE/thesis_share/blob/master/quic_probe/output.txt

**Comment by dtikhonov** [comment]
This is most likely the result of 96f77e2060c43b3356e6a0a060a61ebc43ec0853: now, each connection must have its own socket.  If you test your code with the previous revision, more than one connection at a time should work.

The feature to support zero-sized connection IDs in received packets is meant to increase throughput -- we save eight bytes per packet.  To do so, we need a different way to differentiate between connections, not based on connection ID.  Thinking about this more, however -- and given your experience -- perhaps the user of the library should  be given a choice.

**Comment by sergePSE** [comment]
So, do I have two choices: downgrade a library or use two lsquic engines at the same time as the engine is binded to the particular socket?

**Comment by dtikhonov** [comment]
I'd create a socket for each connection.

**Comment by dtikhonov** [comment]
> Thinking about this more, however -- and given your experience -- perhaps the user of the library should be given a choice.

How about this -- if the option to support zero-sized CIDs is selected, the connections are tracked by the address (meaning a socket per connection).  Otherwise, connections are tracked by ID as before.

**Comment by sergePSE** [comment]
Yes, it would be a great idea. Then it would be still supported a feature of reusable connection. However, I suppose, it would not be a popular option. The other option can be just local socket address check on connection creation.

**Comment by dtikhonov** [comment]
> The other option can be just local socket address check on connection creation.

How do you mean?

**Comment by sergePSE** [comment]
I mean on lsquic_engine_connect it's still possible to check existing connections and its addresses. As this function is called not so frequently, this operation won't cost much. Otherwise, the connection can not even  be processed.

**Comment by dtikhonov** [comment]
In other words, refuse to create a new connection if it's using the same socket as an existing connection?

**Comment by sergePSE** [comment]
Yes, but still I can only suggest this solution if you think that my experience can be a problem for other library users.

**Comment by litespeedtech** [comment]
Fixed in cd7bc3834d5207553534a574404b402a60e7486d -- closing.
