### ISSUE TITLE
Crash when I am trying to invoke lsquic_engine_destroy

### ISSUE THREAD

**Issue by carlcc** [litespeedtech/lsquic-client#40]
Hi, I am using lsquic v1.2 release, and I slightly modified your code to use lsquic as a general purpose translating library.

But I found when I invoke lsquic_engine_destroy function, the program crashes.

On mac and linux, it it sometimes crash, and on windows (by refering your master brach, I ported it to win32), it crashed every time.

when I invoke lsquic_engine_destroy, the program finally dies at the last line of lsquic_malo_destry function (but the 'page' variable is not NULL).

What should I do? Is there anything I should take good care of to use lsquic correctly?

Thank you!

BTW, I don't konw how to use your latest code because I found your master's document is out of date. And I found some comments in the code are out of date, too. Could you please update the document?

**Comment by dtikhonov** [comment]
What were your modifications -- can I take a look at them?

When you say that the master document is out of date, do you mean README.md or some other file?

If comments are out of date, that's a bug.  Feel free to highlight those spots by opening issues -- or even pull requests!

I must say that v1.2 is pretty old -- the code has moved on a lot since then.  Our recommendation is to use the latest code.

**Comment by carlcc** [comment]
The following are all my modifications:

`lsquic_send_ctl.c:350`
I insert an if statement to check if pacing_rate equals 0, if true, set it to 1:
```c
if (pacing_rate == 0)
    pacing_rate = 1;
```

`lsquic_stream.h:68`
I added an enum value STREAM_DATA_BUFFERED = (1 << 29) flag used to hint the engine a stream is readable.
and add a a judgement at `lsquic_stream.c:474`:
```c
static int
stream_readable (const lsquic_stream_t *stream)
{
    /* A stream is readable if one of the following is true: */
    return
        /* - It is already finished: in that case, lsquic_stream_read() will
         *   return 0.
         */
            (stream->stream_flags & STREAM_FIN_REACHED)
        /* - The stream is reset, by either side.  In this case,
         *   lsquic_stream_read() will return -1 (we want the user to be
         *   able to collect the error).
         */
        ||  (stream->stream_flags & STREAM_RST_FLAGS)
        /* - Either we are not in HTTP mode or the HTTP headers have been
         *   received and the headers or data from the stream can be read.
         */
        ||  (!((stream->stream_flags & (STREAM_USE_HEADERS|STREAM_HAVE_UH))
                                                        == STREAM_USE_HEADERS)
            && (stream->uh != NULL
                ||  stream->data_in->di_if->di_get_frame(stream->data_in,
                                                        stream->read_offset)))
        || stream->stream_flags & STREAM_DATA_BUFFERED                           // This is what I added.
    ;
}
```
And I will set this flag after `lsquic_stream_write` is invoked by invoking a function implemented in `lsquic_stream.c` by my own:
```c
void lsqcui_stream_set_is_data_buffered(lsquic_stream_t *stream, int b)
{
    if (b) {
        stream->stream_flags |= STREAM_DATA_BUFFERED;
    } else {
        stream->stream_flags &= ~STREAM_DATA_BUFFERD;
    }
}
```

And to obtain the handshake status, I added a function to get internal status:
```c
int lsquic_is_handshake_done(const lsquic_conn_t *conn)
{
    return (LSCONN_HANDSHAKE_DONE & conn->cn_flags) != 0;
}
```



To use lsquic as a general purpose transporting library, I disabled `COMMON_WRITE_CHECKS()` macro at `lsquic_stream.c:1798`, I added `if (0)`:
```c
#define COMMON_WRITE_CHECKS() if (0) do {
// ...
```

**Comment by carlcc** [comment]
As for "document is out dated", I mean the APIs.txt is not up dated, it seems some key function usage is changed, such as: `lsquic_engine_process_conns` had been removed.

And the comments, I mean the comments above `lsquic_engine_packet_in`'s declare in `lsquic_engine.h`, it says 
```After you add one or more packets, call
 * lsquic_engine_process_conns_with_incoming() to schedule output, if any.
```
but actually `lsquic_engine_process_conns_with_incoming` function had been removed.

**Comment by dtikhonov** [comment]
Interesting: why would `pacing_rate` be zero?

It is not immediately clear to me how these changes would lead to a crash.  Perhaps turning off the write checks allows an unexpected code path?  The bottom line here, however, is that if the original code functions correctly but crashes after your changes, it is these changes that are the cause of the crash.

Thanks for the reminder regarding the documentation in API.txt -- we will fix it.

**Comment by carlcc** [comment]
I don't know why, but I did encounter this situation several times. Maybe the same reason? My modifications made this possible?

I will try the new lsquic version.

Thanks
