### ISSUE TITLE
QUIC congestion controller (question)

### ISSUE THREAD

**Issue by sergePSE** [litespeedtech/lsquic-client#43]
Does lsquic-client implement CUBIC congestion controller?
Is it possible to observe a packet pacing, as it was presented on one of [Google presentations](https://docs.google.com/presentation/d/13LSNCCvBijabnn1S4-Bb6wRlm79gN6hnPFHByEXXptk/present#slide=id.g2591b8f60_14?)?

**Comment by dtikhonov** [comment]
Yes and yes -- see `src/liblsquic/lsquic_cubic.c` and `src/liblsquic/lsquic_pacer.c`.  To observe, pass `-l cubic=debug,pacer=debug` on the command line.
