### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by bshreya74** [litespeedtech/lsquic-client#46]
Hi, 

I am trying to build lsquic-client in windows 10 64bit machine. I have all the dependencies. All the library paths in the target_link_libraries of the CMakeLists.txt is correct. However it still cannot build the lsquic.lib library in either the debug version or the optimized version. These are the errors I got in the optimized version
![release_1](https://user-images.githubusercontent.com/35816503/45951065-1f0f4f80-bfd0-11e8-99d8-2ec0e62b7373.PNG)
![release_2](https://user-images.githubusercontent.com/35816503/45951134-5c73dd00-bfd0-11e8-9012-295c64f73b79.PNG)
![release_3](https://user-images.githubusercontent.com/35816503/45951181-84634080-bfd0-11e8-9bee-3466dfcd69dc.PNG)
![release_4](https://user-images.githubusercontent.com/35816503/45951217-a492ff80-bfd0-11e8-94e5-5b926373dc3a.PNG)

**Comment by dtikhonov** [comment]
The first screenshot seems to indicate that BoringSSL include files are missing some declarations.  Is the BoringSSL version correct?

**Comment by bshreya74** [comment]
The debug version gives LINK error cannot find lsquic.lib
![debug](https://user-images.githubusercontent.com/35816503/45951400-516d7c80-bfd1-11e8-8fae-6437ddc1e28b.PNG)

Please let me know where I am going wrong

**Comment by bshreya74** [comment]
I installed borringssl as directed in the documentation from here:
https://boringssl.googlesource.com/boringssl
Which version of borringssl should I use?

**Comment by dtikhonov** [comment]
AFAIK, _chromium-stable_ branch should work.  Did you build BoringSSL as described in [BUILD-WINDOWS.md](https://github.com/litespeedtech/lsquic-client/blob/master/BUILD-WINDOWS.md)?

**Comment by bshreya74** [comment]
Thanks for pointing that out to me. I built lsquic on ubuntu 16  and it works perfectly. I tried the examples for fetching pages as provided in the examples.txt. However, I was wondering if there is possible way to stream a video using the library. If there is a way please direct me how to do it. Thanks!

**Comment by dtikhonov** [comment]
If streaming video involves something other than the usual HTTP messaging, you'd have to program it yourself.  `http_client` is just a bare-bones program that shows how to use the API.

**Comment by dtikhonov** [comment]
You weren't able to build on Windows in the end?

**Comment by litespeedtech** [comment]
Issue timed out -- closing.
