### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by jes-alpha** [litespeedtech/lsquic-client#48]
Hi I'm trying to build the LSQUIC Client Library but `make` fails when compiling the ibrary. I'm using xubuntu 18.04 Bionic Beaver. This Is the beginning of the error that I receive 

`[ 34%] Built target lsquic
[ 34%] Linking C executable http_client
CMakeFiles/http_client.dir/test/http_client.c.o: In function `sk_X509_num':
/home/jessix/boringssl/include/openssl/x509.h:269: undefined reference to `sk_num'
`

**Comment by dtikhonov** [comment]
Interesting.  Which version of BoringSSL library are you using?

**Comment by jes-alpha** [comment]
How do I check the version ? I downloaded it using 
`git clone https://boringssl.googlesource.com/boringssl`

**Comment by dtikhonov** [comment]
Did you `git checkout chromium-stable`?

**Comment by jes-alpha** [comment]
Managed to install the library by using the alternate method (without root).

**Comment by dtikhonov** [comment]
I see the bug.  Step 2 has

```
cmake -DBORINGSSL_INCLUDE=$BORINGSSL_SOURCE/include \
                                -DBORINGSSL_LIB=$HOME/tmp/boringssl-libs .
make
```

`BORINGSSL_LIB` is set incorrectly when the library is installed into `/usr/local/lib`.
