### ISSUE TITLE
[Linux / 1.17.0] unit test failures: parse_packet, frame_rw

### ISSUE THREAD

**Issue by INRIX-joel-winarske** [litespeedtech/lsquic-client#49]
40: Test command: /home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_parse_packet_in
40: Test timeout computed to be: 10000000
40: 
40: =================================================================
40: ==10033==ERROR: LeakSanitizer: detected memory leaks
40: 
40: Direct leak of 2740 byte(s) in 2 object(s) allocated from:
40:     #0 0x4b9a08  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_parse_packet_in+0x4b9a08)
40:     #1 0x4ff040  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_parse_packet_in+0x4ff040)
40:     #2 0x4eb211  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_parse_packet_in+0x4eb211)
40:     #3 0x4eb049  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_parse_packet_in+0x4eb049)
40:     #4 0x7f84796a782f  (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
40: 
40: SUMMARY: AddressSanitizer: 2740 byte(s) leaked in 2 allocation(s).
40/53 Test #40: parse_packet_in ..................***Failed    0.01 sec

...

test 47
      Start 47: frame_rw

47: Test command: /home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw
47: Test timeout computed to be: 10000000
47: 
47: =================================================================
47: ==10047==ERROR: LeakSanitizer: detected memory leaks
47: 
47: Direct leak of 6944 byte(s) in 62 object(s) allocated from:
47:     #0 0x4bc600  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4bc600)
47:     #1 0x516102  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x516102)
47:     #2 0x4fe759  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4fe759)
47:     #3 0x4f98df  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4f98df)
47:     #4 0x4f5009  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4f5009)
47:     #5 0x4f48ee  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4f48ee)
47:     #6 0x4ee021  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4ee021)
47:     #7 0x4edb7d  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4edb7d)
47:     #8 0x7fc9536ad82f  (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
47: 
47: Direct leak of 1008 byte(s) in 9 object(s) allocated from:
47:     #0 0x4bc600  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4bc600)
47:     #1 0x516102  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x516102)
47:     #2 0x4fe759  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4fe759)
47:     #3 0x4fdb00  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4fdb00)
47:     #4 0x4fcf86  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4fcf86)
47:     #5 0x4f914a  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4f914a)
47:     #6 0x4f4fe7  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4f4fe7)
47:     #7 0x4f48ee  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4f48ee)
47:     #8 0x4ee021  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4ee021)
47:     #9 0x4edb7d  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4edb7d)
47:     #10 0x7fc9536ad82f  (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
47: 
47: Indirect leak of 36569088 byte(s) in 62 object(s) allocated from:
47:     #0 0x4bc7f8  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4bc7f8)
47:     #1 0x518c5c  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x518c5c)
47:     #2 0x517a6b  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x517a6b)
47:     #3 0x516719  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x516719)
47:     #4 0x5163fc  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x5163fc)
47:     #5 0x4feb4a  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4feb4a)
47:     #6 0x4f98df  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4f98df)
47:     #7 0x4f5009  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4f5009)
47:     #8 0x4f48ee  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4f48ee)
47:     #9 0x4ee021  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4ee021)
47:     #10 0x4edb7d  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4edb7d)
47:     #11 0x7fc9536ad82f  (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
47: 
47: Indirect leak of 5308416 byte(s) in 9 object(s) allocated from:
47:     #0 0x4bc7f8  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4bc7f8)
47:     #1 0x518c5c  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x518c5c)
47:     #2 0x517a6b  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x517a6b)
47:     #3 0x516719  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x516719)
47:     #4 0x5163fc  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x5163fc)
47:     #5 0x4feb4a  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4feb4a)
47:     #6 0x4fdb00  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4fdb00)
47:     #7 0x4fcf86  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4fcf86)
47:     #8 0x4f914a  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4f914a)
47:     #9 0x4f4fe7  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4f4fe7)
47:     #10 0x4f48ee  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4f48ee)
47:     #11 0x4ee021  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4ee021)
47:     #12 0x4edb7d  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4edb7d)
47:     #13 0x7fc9536ad82f  (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
47: 
47: Indirect leak of 248 byte(s) in 62 object(s) allocated from:
47:     #0 0x4bc478  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4bc478)
47:     #1 0x517e66  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x517e66)
47:     #2 0x51753a  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x51753a)
47:     #3 0x5166f9  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x5166f9)
47:     #4 0x5163fc  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x5163fc)
47:     #5 0x4feb4a  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4feb4a)
47:     #6 0x4f98df  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4f98df)
47:     #7 0x4f5009  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4f5009)
47:     #8 0x4f48ee  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4f48ee)
47:     #9 0x4ee021  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4ee021)
47:     #10 0x4edb7d  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4edb7d)
47:     #11 0x7fc9536ad82f  (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
47: 
47: Indirect leak of 36 byte(s) in 9 object(s) allocated from:
47:     #0 0x4bc478  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4bc478)
47:     #1 0x517e66  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x517e66)
47:     #2 0x51753a  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x51753a)
47:     #3 0x5166f9  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x5166f9)
47:     #4 0x5163fc  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x5163fc)
47:     #5 0x4feb4a  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4feb4a)
47:     #6 0x4fdb00  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4fdb00)
47:     #7 0x4fcf86  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4fcf86)
47:     #8 0x4f914a  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4f914a)
47:     #9 0x4f4fe7  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4f4fe7)
47:     #10 0x4f48ee  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4f48ee)
47:     #11 0x4ee021  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4ee021)
47:     #12 0x4edb7d  (/home/joel/git/ipipe/build/lsquic_ext-prefix/src/lsquic_ext-build/test/unittests/test_frame_rw+0x4edb7d)
47:     #13 0x7fc9536ad82f  (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
47: 
47: SUMMARY: AddressSanitizer: 41885740 byte(s) leaked in 213 allocation(s).
47/53 Test #47: frame_rw .........................***Failed   22.83 sec

**Comment by dtikhonov** [comment]
Thank you for your report.  `test_parse_packet_in` has been fixed in dee31d56.

**Comment by dtikhonov** [comment]
The memory leak in unit test `test_frame_rw` has been fixed in db5f69e34.

**Comment by litespeedtech** [comment]
The two bugs have been fixed -- closing.
