### ISSUE TITLE
Missing event2/event.h header file

### ISSUE THREAD

**Issue by LipiLee** [litespeedtech/lsquic-client#5]
I have got a build error when test/prog.c was compiled.
The c source file is including the event2/event.h header file is not found in the project.

Can anybody check it for me?
Thanks

**Comment by dtikhonov** [comment]
You need libevent2 library and header files.

**Comment by LipiLee** [comment]
@dtikhonov Thanks for your help. My build is successful. But, I found a minor build bug. May I submit a PR?

**Comment by dtikhonov** [comment]
> May I submit a PR?

Of course: we are glad to receive PRs!
