### ISSUE TITLE
[Linux / 1.17.0] all memcheck unit tests fail

### ISSUE THREAD

**Issue by INRIX-joel-winarske** [litespeedtech/lsquic-client#50]
Configure your build as follows:

install valgrind on your workstation
`sudo apt-get install valgrind`

Add to line below enable_testing() in the test/unittests/CMakeLists.txt
`find_program(CTEST_MEMORYCHECK_COMMAND NAMES valgrind)`
this will generate DartConfiguration.tcl in your build dir

from build folder execute memcheck on the unittests
`ctest test -T memcheck -V`

**Comment by dtikhonov** [comment]
Yeah: valgrind does not work when clang's AddressSanitizer is on.  Compile with gcc and run valgrind again.

**Comment by litespeedtech** [comment]
Invalid -- closing.
