### ISSUE TITLE
How can I post some data (not file)?

### ISSUE THREAD

**Issue by luodijia** [litespeedtech/lsquic-client#53]
Can the -P parameter supports to post some string?

**Comment by dtikhonov** [comment]
Not, at the moment, no:

```
        case 'P':
            client_ctx.payload = optarg;
            if (0 != stat(optarg, &st))
            {
                perror("stat");
                exit(2);
            }
```

But pull requests are welcome!

**Comment by litespeedtech** [comment]
Question answered: closing.

**Comment by luodijia** [comment]
Thx. Then how can I modify some code to support posting some string? Which interface or code segment can put the contents of file to the request body? Wait for your advice! Thx again!

**Comment by luodijia** [comment]
I will try, Thx a lot!
