### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by fanto88** [litespeedtech/lsquic-client#54]
I'm not able to build.

Compile the library

```
cmake -DBORINGSSL_INCLUDE=$BORINGSSL_SOURCE/include \
                                -DBORINGSSL_LIB=$HOME/tmp/boringssl-libs .
make
```

Appears that error:

`/usr/local/lib/lsquic-client/src/liblsquic/lsquic_parse_iquic_common.c:8:10: fatal error: openssl/rand.h: No such file or directory
 #include <openssl/rand.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
src/liblsquic/CMakeFiles/lsquic.dir/build.make:206: recipe for target 'src/liblsquic/CMakeFiles/lsquic.dir/lsquic_parse_iquic_common.c.o' failed
make[2]: *** [src/liblsquic/CMakeFiles/lsquic.dir/lsquic_parse_iquic_common.c.o] Error 1
CMakeFiles/Makefile2:172: recipe for target 'src/liblsquic/CMakeFiles/lsquic.dir/all' failed
make[1]: *** [src/liblsquic/CMakeFiles/lsquic.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
`

thanks, Davide.

**Comment by dtikhonov** [comment]
Does `$BORINGSSL_SOURCE/include` contain BoringSSL header files?  Try

```
ls $BORINGSSL_SOURCE/include/openssl.rand.h
```

**Comment by dtikhonov** [comment]
It seems that your endpoint does not send any UDP packets back.  It may be either an ingress or egress issue, it's hard to tell.

With regard to Chrome, it complains about an invalid certificate when HTTPS is used.  I doubt that Chrome is able to use QUIC to connect to your server:

![image](https://user-images.githubusercontent.com/4528576/50113875-2b8ef700-0211-11e9-8232-1c6d5416fd23.png)

If you install HTTP/2 and SPDY Indicator plugin for Chrome, you should be able to tell when QUIC is used: the lightning bolt should be green:

![image](https://user-images.githubusercontent.com/4528576/50114020-8aed0700-0211-11e9-974a-7409ddbf64fd.png)

**Comment by fanto88** [comment]
It's not possibile to use a self certificate? I can use quic on my website since I'm using a self signed certificate. It's possible to use a self signed certificate with that client?

**Comment by dtikhonov** [comment]
Chrome won't let you.

LSQUIC client is fine with that, but: no UDP packets are coming back.  You can check it by turning on debugging message or running `tcpdump`.  Is that UDP port open?

**Comment by fanto88** [comment]
Actually i'm able to use Self Signed Certificate on Chrome and use QUIC
![untitled](https://user-images.githubusercontent.com/10716240/50115893-01f1c200-0249-11e9-98ce-423e394df045.png)

Since i can use QUIC on Chrome i suppose the port is open, i'm correct? I'm new with those things.

**Comment by dtikhonov** [comment]
I see what's going on.  The latest lsquic-client sends Q044 Client Hello message by default, while your server only understands Q043.  Add `-o version=Q043` on the command line and the request will work.

**Comment by fanto88** [comment]
Gonna try it as soon I will be at home!
Thanks a lot for the help. Can I ask 2 question to keep me busy in those days? 
I need to send some information (a string that is name-value-timestamp) from the client to the server and the server should just output it on a page. Is that possibile using this client? Which language should I use on the server(php is fine?)? 
Ps: send packet using quic protocol

**Comment by dtikhonov** [comment]
Any language on the server will do. The transport is transparent.

The demo client distributed with the library, `http_client` supports sending `GET` and `POST` methods. See the output of the help (`-h`) screen, in particular `-p`, `-M`, and `-P` flags.  The simplest thing to do is

```
-p /some-path.php?name=value
```

**Comment by fanto88** [comment]
Let me close this question since we are speaking about another problem. Gonna create a new question if unable to create the script that I need.

Thanks a lot for all the help, sir.
