### ISSUE TITLE
Handshake fails versus this public URL: https://bitdash-a.akamaihd.net/content/sintel/sintel.mpd

### ISSUE THREAD

**Issue by irina-nitu** [litespeedtech/lsquic-client#68]
Handshake fails versus this public URL: https://bitdash-a.akamaihd.net/content/sintel/sintel.mpd
It seems that the client cannot decrypt the packets coming from this server.
The chromium quic client for example interops ok.

**Comment by dtikhonov** [comment]
I can reproduce the issue: decryption indeed fails.  We will work on figuring out why.

**Comment by litespeedtech** [comment]
This has been fixed in 1.19.5 (see 8437e4a4f29e39f7de1fbf4518af0e370380ce67). Thank you for your report!
