### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Zxy675272387** [litespeedtech/lsquic-client#73]
when I cd lsquic-client  and  make,the errors as below,it seems that my libevent version is not suitable,but I don't know how fix it 
[ 35%] Linking C executable http_client
CMakeFiles/http_client.dir/test/http_client.c.o: In function `create_another_conn_or_stop':
/home/b/quictest/lsquic/lsquic-client/test/http_client.c:292: undefined reference to `event_free'
CMakeFiles/http_client.dir/test/http_client.c.o: In function `http_client_on_conn_closed':
/home/b/quictest/lsquic/lsquic-client/test/http_client.c:332: undefined reference to `event_new'
CMakeFiles/http_client.dir/test/prog.c.o: In function `prog_run':
/home/b/quictest/lsquic/lsquic-client/test/prog.c:345: undefined reference to `event_new'

**Comment by dtikhonov** [comment]
You need libevent2.  What OS are you using?

**Comment by Zxy675272387** [comment]
deibian 9.5

**Comment by dtikhonov** [comment]
libevent on my system is 2.0.21.  If the API were incompatible, lsquic would not have compiled -- but what you are getting are link errors.

**Comment by dtikhonov** [comment]
I just downloaded libevent 2.1.10 and compiled, linked, and ran lsquic using it:

```
cmake -DCMAKE_LIBRARY_PATH=$HOME/local/lib -DCMAKE_INCLUDE_PATH=$HOME/local/include .

**Comment by Zxy675272387** [comment]
I enter the source file http_client.c,find you use include<event2/event.h>,but on my os ,if I include<event2/event.h>to use libevent it can't be compiled. If I change the include into include<event.h>,the error is http_client.c:286:30: error: unknown type name ‘evutil_socket_t’
 create_another_conn_or_stop (evutil_socket_t sock, short events, void *ctx),is this happened because of my OS?

**Comment by dtikhonov** [comment]
It may be because you don't have libevent development package installed.  On Ubuntu, libevent header files are in `/usr/include/event2` and are distrubuted in `libevent-dev` package.  I don't have experience with Debian, but it should be similar.

**Comment by dtikhonov** [comment]
If everything else fails, you can do what I did above: compile and install a separate copy of libevent and use that.

**Comment by Zxy675272387** [comment]
emmm....I find that I have event.h in both /usr/include/event2 and /usr/include/,the first is unlinked,and the scecond is linked,does this explain that  what I am getting are link errors?

**Comment by dtikhonov** [comment]
> there is no error,but the make msg is

Yes, those are test files: by default, everything is built.  You can type `make http_client` to compile just the client program.

**Comment by litespeedtech** [comment]
No feedback for a while -- closing bug.
