### ISSUE TITLE
client does not support any of the server-specified versions

### ISSUE THREAD

**Issue by vunhatminh241191** [litespeedtech/lsquic-client#74]
Hi,

I am trying to using ./http_client to talk with my quic server, but it returns this error to me
`[ERROR] [QUIC:12718164802224998270] conn: Abort connection: client does not support any of the server-specified versions`
The command that I am using for is
`./http_client -t -H sni.com -s 10.11.0.122:4433`, which SNI is stored in my default SSL file and I am using TLSvs1.3.

This test failed on both master and ietf-base-draft-20 branches.

Do you guys have any recommendation on that.

**Comment by dtikhonov** [comment]
What is your QUIC server?

**Comment by dtikhonov** [comment]
> What is your QUIC server?

That is to say: which QUIC server are you trying to connect to?  Do you know which QUIC version it supports?

**Comment by vunhatminh241191** [comment]
My server is supported quic version draft 20. I think there is something related to patches for BoringSSL. But I don't know how to apply this patch to the new build of BoringSSL

**Comment by dtikhonov** [comment]
Version negotiation occurs before SSL.  Assuming the client sends FF000014 version, why does your server reply with a version negotiation packet if it supports FF000014?

You can follow directions in .travis.yml to check out the correct version of BoringSSL and apply the patch.

**Comment by vunhatminh241191** [comment]
My server support FF000014 version. I don't know why it happens but after applying the fix patch for boringssl, it works fine.
