### ISSUE TITLE
unittest cmakelists 

### ISSUE THREAD

**Issue by amoldeshpande** [litespeedtech/lsquic-client#9]
I just noticed that one of the changes that was made in merging my Windows pull request  was to separate unittests by MSVC and not MSVC, instead of defining compiler flags by the same and keeping the list of tests common

My concern is that this makes it easy to miss for Windows any new tests that get added. I think I already found a test_frame_rw   that should be compiled for windows but is not.

**Comment by dtikhonov** [comment]
This is a valid concern.  We'll try to take care of it next time we muck with the makefiles.

**Comment by litespeedtech** [comment]
This has been addressed on master.  Closing.
